# Generated by Django 3.0.8 on 2021-05-28 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plan', '0004_auto_20210528_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='chart',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='plan.Chart'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
