# Generated by Django 3.0.8 on 2021-05-28 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0005_auto_20210528_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='chart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plan.Chart'),
        ),
    ]
