# Generated by Django 3.0.8 on 2021-05-30 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0010_auto_20210530_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='chart',
        ),
    ]
