# Generated by Django 3.0.8 on 2021-05-31 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0014_auto_20210531_0141'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
