# Generated by Django 3.0.8 on 2021-05-31 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0017_chart_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
