# Generated by Django 3.0.8 on 2021-06-05 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0018_chart_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='data',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chart',
            name='envColor',
            field=models.CharField(default='0.0.0.0', max_length=255),
        ),
        migrations.AddField(
            model_name='chart',
            name='fill',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chart',
            name='graphsize',
            field=models.CharField(default='col-md', max_length=255),
        ),
        migrations.AddField(
            model_name='chart',
            name='graphtype',
            field=models.CharField(default='doughnut', max_length=255),
        ),
        migrations.AddField(
            model_name='chart',
            name='hoverenvcolor',
            field=models.CharField(default='0.0.0.0', max_length=255),
        ),
        migrations.AddField(
            model_name='chart',
            name='hoverpointcolor',
            field=models.CharField(default='0.0.0.0', max_length=255),
        ),
        migrations.AddField(
            model_name='chart',
            name='labeltitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chart',
            name='lineColor',
            field=models.CharField(default='0.0.0.0', max_length=255),
        ),
        migrations.AddField(
            model_name='chart',
            name='pointcolor',
            field=models.CharField(default='0.0.0.0', max_length=255),
        ),
        migrations.AddField(
            model_name='chart',
            name='tension',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chart',
            name='backgroundcolor',
            field=models.CharField(default='0.0.0.0', max_length=255),
        ),
        migrations.AlterField(
            model_name='chart',
            name='bordercolor',
            field=models.CharField(default='0.0.0.0', max_length=255),
        ),
        migrations.AlterField(
            model_name='chart',
            name='hoverbordercolor',
            field=models.CharField(default='0.0.0.0', max_length=255),
        ),
    ]
