# Generated by Django 3.0.8 on 2021-06-23 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0019_auto_20210605_0213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='backgroundcolor',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='bordercolor',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='borderwidth',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='envColor',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='fill',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='graphsize',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='graphtype',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='hoverbordercolor',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='hoverborderwidth',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='hoverenvcolor',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='hoverpointcolor',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='label',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='labeltitle',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='lineColor',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='pointcolor',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='tension',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='title',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='xaxistitle',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='yaxistitle',
        ),
    ]
