# Generated by Django 3.0.8 on 2021-06-23 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0021_auto_20210623_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='userid',
            field=models.CharField(default='bob', max_length=32),
        ),
    ]
