# Generated by Django 3.0.8 on 2021-06-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0023_auto_20210623_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='title',
            field=models.CharField(default='Graph', max_length=32),
        ),
        migrations.AlterField(
            model_name='chart',
            name='data',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
