# Generated by Django 3.0.8 on 2021-06-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0024_auto_20210625_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='graph',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
